# Generated by Django 2.2.5 on 2019-10-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=100, verbose_name='描述')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('pic', models.ImageField(upload_to='api/img/money/', verbose_name='收款码图片')),
            ],
            options={
                'verbose_name': '收款码',
                'verbose_name_plural': '收款码',
            },
        ),
    ]
