# Generated by Django 2.2.5 on 2019-09-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='名称')),
                ('size', models.CharField(max_length=80, verbose_name='大小')),
                ('price', models.IntegerField(default=100, verbose_name='价格')),
                ('description', models.CharField(max_length=500, verbose_name='描述')),
            ],
            options={
                'verbose_name': '大闸蟹',
                'verbose_name_plural': '大闸蟹',
            },
        ),
    ]
