# Generated by Django 2.2.5 on 2019-09-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crab',
            name='net',
            field=models.CharField(default='元/两', max_length=80, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='crab',
            name='description',
            field=models.TextField(max_length=500, verbose_name='描述'),
        ),
    ]
