# Generated by Django 2.2.5 on 2019-09-11 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20190911_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='line_items',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='market.Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('未付款', '未付款'), ('已付款', '已付款'), ('已发货', '已发货'), ('完成', '完成')], default='未付款', max_length=10, verbose_name='状态'),
        ),
    ]
