# Generated by Django 2.2.5 on 2019-09-11 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_auto_20190911_0502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineitem',
            options={'verbose_name': '物品', 'verbose_name_plural': '物品'},
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='crab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Crab', verbose_name='大闸蟹'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Customer', verbose_name='客户'),
        ),
        migrations.CreateModel(
            name='CrabImage',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(upload_to='crab_images/')),
                ('crab', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.Crab')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
    ]
