# Generated by Django 2.0 on 2019-09-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20190912_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crab',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='描述'),
        ),
    ]
