# Generated by Django 2.0 on 2019-09-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20190912_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='crab',
            name='original_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='原价'),
        ),
        migrations.AlterField(
            model_name='crab',
            name='price',
            field=models.IntegerField(default=100, verbose_name='实际价格'),
        ),
    ]
