# Generated by Django 2.0 on 2019-09-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20190912_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='12345678', max_length=50, verbose_name='密码'),
            preserve_default=False,
        ),
    ]
