# Generated by Django 2.2.5 on 2019-09-17 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crab',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='名称')),
                ('size', models.CharField(max_length=80, verbose_name='大小')),
                ('price', models.IntegerField(default=100, verbose_name='实际价格')),
                ('original_price', models.IntegerField(blank=True, null=True, verbose_name='原价')),
                ('net', models.CharField(default='元', max_length=80, verbose_name='单位')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '大闸蟹',
                'verbose_name_plural': '大闸蟹',
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0, verbose_name='数量')),
                ('crab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Crab', verbose_name='大闸蟹')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
            },
        ),
        migrations.CreateModel(
            name='CrabImage',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(upload_to='img/crab_images/', verbose_name='图片')),
                ('crab', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='goods.Crab')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
    ]
