# Generated by Django 2.2.5 on 2019-09-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_lineitem_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineItem',
        ),
    ]
