# Generated by Django 2.2.5 on 2019-09-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_delete_lineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crabimage',
            name='pic',
            field=models.ImageField(upload_to='api/img/crab_images/', verbose_name='图片'),
        ),
    ]
