# Generated by Django 2.2.5 on 2019-09-23 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_lineitem_order'),
        ('cart', '0003_auto_20190923_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='line_items',
        ),
        migrations.CreateModel(
            name='CartLineItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0, verbose_name='数量')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_line_items', to='cart.Cart')),
                ('crab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Crab', verbose_name='大闸蟹')),
            ],
            options={
                'verbose_name': '购物车物品',
                'verbose_name_plural': '购物车物品',
            },
        ),
    ]
