# Generated by Django 2.2.5 on 2019-09-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_delete_lineitem'),
        ('cart', '0004_auto_20190923_0016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartlineitem',
            unique_together={('cart', 'crab')},
        ),
    ]
