# Generated by Django 2.2.5 on 2019-09-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='地址'),
        ),
    ]
