# Generated by Django 2.2.5 on 2019-09-23 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_lineitem_order'),
        ('order', '0002_order_line_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='line_items',
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=0, verbose_name='数量')),
                ('crab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Crab', verbose_name='大闸蟹')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_line_items', to='order.Order')),
            ],
            options={
                'verbose_name': '订单物品',
                'verbose_name_plural': '订单物品',
            },
        ),
    ]
