# Generated by Django 2.2.5 on 2019-10-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190923_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_address',
            field=models.CharField(default='', max_length=80, verbose_name='收件人地址'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(default='', max_length=80, verbose_name='收件人姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(default='', max_length=80, verbose_name='收件人电话'),
            preserve_default=False,
        ),
    ]
